version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:18.06.3-ce-git
    working_directory: /work/workspace

  git-executor:
    docker:
      - image: alpine/git
    working_directory: /work/workspace

jobs:
  start:
    executor: git-executor
    steps:
      - attach_workspace:
          at: /work/workspace
      - checkout
      - persist_to_workspace:
          root: /work/workspace
          paths: .

  build-all:
    executor: docker-executor
    steps:
      - setup_remote_docker

      - attach_workspace:
          at: /work/workspace

      - run: |
          docker build -t cocotb_image .

          docker run --name cocotb_container cocotb_image bash -c "source /opt/venv/bin/activate && cd /pbt && SIM=verilator coverage run --source=tests -m pytest && coverage html && coverage xml && coverage-badge -o htmlcov/coverage.svg && mkdir -p /test-reports/pbt && cp /pbt/junit.xml /test-reports/pbt && mkdir -p /coverage-reports/pbt && cp -r /pbt/coverage.xml /pbt/htmlcov /coverage-reports/pbt"

          docker cp pbt_container:coverage-reports .
          docker cp pbt_container:test-reports .
          docker rm pbt_container

      - persist_to_workspace:
          root: /work/workspace
          paths:
            - test-reports/pbt
            - coverage-reports/pbt

  finish:
    executor: git-executor

    steps:
      - attach_workspace:
          at: /work/workspace

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - store_artifacts:
          path: coverage-reports

workflows:
  version: 2.1

  full:
    jobs:
      - start
      - build-all
          requires:
            - start
      - finish:
          requires:
            - build-all
